import type { ContextStoreAdapter } from './types.js';

export interface MigrationResult {
  contexts: number;
  bubbles: number;
}

export interface MigrateOptions {
  /**
   * `copy` adds to whatever the target already holds (the default).
   * `replace` empties the target first.
   */
  mode?: 'copy' | 'replace';
}

async function clear(target: ContextStoreAdapter): Promise<void> {
  for (const bubble of await target.listBubbles()) {
    await target.deleteBubble(bubble.id, true);
  }
  for (const entry of await target.listContexts()) {
    await target.deleteContext(entry.id);
  }
}

/**
 * Copy every context and bubble from one store into another.
 *
 * The source is only ever read, so a migration cannot damage the data the user
 * already has — if the target write fails halfway, the original store is still
 * intact and the operation can simply be retried.
 *
 * Everything is read from the source *before* the target is touched. That
 * ordering is what makes `replace` safe when both handles happen to point at the
 * same database: clearing first would delete the very rows about to be copied.
 *
 * Bubbles are written first so that contexts referencing them land on a target
 * where those bubbles already exist.
 */
export async function migrateStore(
  source: ContextStoreAdapter,
  target: ContextStoreAdapter,
  options: MigrateOptions = {},
): Promise<MigrationResult> {
  const { mode = 'copy' } = options;

  const bubbles = await source.listBubbles();
  const contexts = await source.listContexts();

  if (mode === 'replace') {
    await clear(target);
  }

  // Ids are regenerated by the target's own `create` calls, so a map carries the
  // source id forward to the new one and keeps context→bubble links correct.
  const bubbleIdMap = new Map<string, string>();

  for (const bubble of bubbles) {
    const created = await target.createBubble(bubble.name, bubble.description);
    bubbleIdMap.set(bubble.id, created.id);
  }

  for (const entry of contexts) {
    const mappedBubbleId = entry.bubbleId ? bubbleIdMap.get(entry.bubbleId) : undefined;
    await target.saveContext(entry.content, entry.tags, entry.source, mappedBubbleId);
  }

  return { contexts: contexts.length, bubbles: bubbles.length };
}
